os: linux
sudo: required
language: "minimal"
services:
  - docker
env:
  - DOCKER_IMAGE="toliak/bootstrap-cpp"

before_script:
  - docker pull $DOCKER_IMAGE

jobs:
  include:
    - name: "checks"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/checks.sh
    - name: "tests"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/tests.sh
    - name: "coverage"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/coverage.sh


notifications:
  email: false